### ISSUE TITLE
Connection pool is getting full

### ISSUE THREAD

**Issue by Mishelder** [Mishelder/to_do#2]
06-Jul-2021 21:12:01.055 SEVERE [http-nio-8081-exec-75] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [com.miaskor.servlets.LoginServlet] in context with path [] threw exception [Servlet execution threw an exception] with root cause
	org.postgresql.util.PSQLException: FATAL: sorry, too many clients already
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:613)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:161)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
		at org.postgresql.Driver.makeConnection(Driver.java:465)
		at org.postgresql.Driver.connect(Driver.java:264)
		at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
		at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
		at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
		at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
		at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
		at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
		at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
		at com.miaskor.database.DataSourceFactory.getDataSource(DataSourceFactory.java:31)
		at com.miaskor.database.ConnectionManager.<clinit>(ConnectionManager.java:11)
		at com.miaskor.dao.ClientDaoImpl.readByLogin(ClientDaoImpl.java:111)
		at com.miaskor.validator.LoginClientValidator.isValid(LoginClientValidator.java:22)
		at com.miaskor.service.LoginClientService.loginClient(LoginClientService.java:27)
		at com.miaskor.servlets.LoginServlet.doPost(LoginServlet.java:43)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
		at com.miaskor.filter.LoginFilter.doFilter(LoginFilter.java:35)
		at javax.servlet.http.HttpFilter.doFilter(HttpFilter.java:57)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Mishelder** [comment]
SELECT * FROM pg_stat_activity;  by this command i found out that application got 10 connections to the DB as specified in the database.properties, but after i redeployed application old connections didn't remove, therefore after ten redeploying application is fall down -> more than 100 connections db is not maintain
